# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "CS373 Spring 2016: Kristine Domingo"

# URL
baseurl:            "/cs373-blog"
permalink:          /:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/cs373-blog/about"
  - name:           "Homepage"
    href:           "//kristinedomingo.com"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
